services:
  - type: web
    name: backend
    runtime: python
    buildCommand: pip install -r requirements.txt && prisma py fetch && prisma generate
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        sync: false
